//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiegeCombat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casillas
    {
        public int IdPartida { get; set; }
        public int IdJugador { get; set; }
        public int IdCasillas { get; set; }
        public string Coordenada { get; set; }
    }
}
