//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiegeCombat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePartida
    {
        public int IdDetalle { get; set; }
        public string Posicion { get; set; }
        public string Movimiento { get; set; }
        public Nullable<int> IdJugador { get; set; }
        public string Resultado { get; set; }
        public int IdPartida { get; set; }
    
        public virtual Partida Partida { get; set; }
    }
}
