//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiegeCombat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitaciones
    {
        public int IdInvitaciones { get; set; }
        public Nullable<int> IdHost { get; set; }
        public Nullable<int> IdOponente { get; set; }
        public Nullable<int> Respuesta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
