//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiegeCombat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiegeCombatEntities : DbContext
    {
        public SiegeCombatEntities()
            : base("name=SiegeCombatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Casillas> Casillas { get; set; }
        public DbSet<Invitaciones> Invitaciones { get; set; }
        public DbSet<Jugada> Jugada { get; set; }
        public DbSet<Jugador> Jugador { get; set; }
        public DbSet<Partida> Partida { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
