//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiegeCombat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int IdPartida { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdGanador { get; set; }
        public string Tiempo { get; set; }
        public int IdJugadorUno { get; set; }
        public int IdJugadorDos { get; set; }
        public int IdJugada { get; set; }
        public int Estatus { get; set; }
    
        public virtual Jugador Jugador { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
